config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 10, maximum: 1000}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, uniqueness: { case_sensitive: false}, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: { case_sensitive: false}, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def show
    
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(new_update_article)
        @article.user = current_user
        if @article.save
        flash[:notice] = "Article Created sucessfuly"
        # redirect_to article_path(@article)
        redirect_to @article
        else
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        
        if @article.update(new_update_article)
            flash[:notice] = "Article updated sucessfully"
            redirect_to @article
        else
            render 'edit'
        end

    end

    def destroy
        @article.destroy
        redirect_to @article
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end
    def new_update_article
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only Edit or Delete your own article"
            redirect_to @article
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
    before_action :require_user, except: [:index, :show]
    before_action :require_admin_user, except: [:index, :show]
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category sucessfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def index
        @category = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @article_category = @category.articles.paginate(page: params[:page], per_page: 5)
        @categories = @category.articles
    end

    def edit 
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category was succesfully updated"
            redirect_to @category
        else
            render 'edit'
        end
    end
    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin_user
        if !current_user.admin?
            flash[:alert] = "Only Admin can create a new Category"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in succesfully"
            redirect_to user
        else
            flash.now[:alert] = "Login credential miss match"
            render 'new'
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out sucessfully"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to Project2 #{@user.username}, you have successfuly signed up"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        
    end

    def update
      
        if @user.update(user_params)
            flash[:notice] = "Your account suceesfuly updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def show
        @article = @user.articles.paginate(page: params[:page], per_page: 5)
    end
    
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:alert] = "Account and all associated articles sucessfully deleted"
        if current_user.admin?
            redirect_to users_path
        else
            redirect_to root_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only Edit or Delete your own profile"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, option = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = option[:size]
        image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag( image_src, alt: user.username, class: "rounded shadow mx-auto d-block" )
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container" id="listing-container">
        
        <% obj_article.each do |article| %>
        <div class="row justify-content-md-center mt-4">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    by <%= link_to article.user.username, user_path(article.user) %>
                    <% if article.categories.any? %>
                        <div class="mt-1"><%= render article.categories %></div>
                    <% end %>
                </div>
                <div class="card-body">
                <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                <p class="card-text"><%= truncate article.description, length: 100 %></p>
                <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
                <% if logged_in? and (article.user == current_user || current_user.admin?) %>
                    <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
                    <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure" }, class: "btn btn-outline-danger" %>
                <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>created <%= time_ago_in_words(article.created_at) %> ago edited <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
            </div>
            </div>
        </div>
        <% end %>

    </div>

app/views/articles/_form.html.erb
<div class="container">

<div class="row justify-content-center">
    <div class="col-sm-10">
        <%= render "shared/errors", obj: @article %>
        <%= form_with(model: @article, local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :title, class: 'col-sm-2 col-form-label' %></br>
            <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control', placeholder: "Title of Article" %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :description, class: 'col-sm-2 col-form-label' %></br>
            <div class="col-sm-10">
            <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: "Desc for Artilce" %>
            </div>
        </div>
        
        <div class="form-group row">
            <%= f.label :description, class: 'col-sm-2 col-form-label' %></br>
            <% hidden_field_tag "article[category_ids][]", nil %>
            <div class="col-sm-10 mt-2">
                <div class="custom-control custom-checkbox">
                    <% Category.all.each do |f| %>
                        <%= check_box_tag "article[category_ids][]", f.id, @article.category_ids.include?(f.id), id: dom_id(f), class: "checkbox-inline" %>
                        <%= label_tag dom_id(f), f.name %></br>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <%= f.submit class: 'btn btn-outline-success' %>
        </div>
        <% end %>
        
        </div>
        <small class="mb-4"><%= link_to '[ Cancel and return to article listing ]', articles_path  %></small>
    
</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit article</h1>
    <%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4">Articles listing page</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles', obj_article: @articles %>
<div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
    <h1 class="text-center mt-4 mb-4">Create a new article</h1>

    <%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4 mb-4"><%= @article.title %></h1>

    <div class="container" id="listing-container">
        
        <div class="row justify-content-md-center mt-4">
        <div class="col-8">
            <div class="card text-center">
                <div class="card-header">
                
                <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                by <%= link_to @article.user.username, user_path(@article.user) %>
                
                    <% if @article.categories.any? %>
                    <div class="mt-2"><%= render @article.categories %></div>
                    <% end %>
                
                </div>
                <div class="card-body">
                <div class="card-text text-left"><%= simple_format( @article.description ) %></div>
                <%= link_to 'Article listing', articles_path, class: "btn btn-outline-success" %>
                <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
                    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure" }, class: "btn btn-outline-danger" %>
                <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>created <%= time_ago_in_words(@article.created_at) %> ago edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
                </div>
            </div>
            </div>
        </div>


    </div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-success mr-1" %>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>
    <%= form_with(model: @category, local: true) do |f| %>
    <div class="form-group row justify-content-center mt-4">
        <%= f.label :name, "Category Name:", class: 'col-sm-2 col-form-label' %></br>
        <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter a Name" %>
        </div>
    </div>
    <div class="form-group row justify-content-center mt-4">
        <%= f.submit class: 'btn btn-outline-success' %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit Category Name</h1>

<div class="container">

<div class="row justify-content-center">
    <div class="col-sm-12">
        <%= render 'form' %>
    </div>
    <small ><%= link_to '[ Cancel and return Category ]', category_path  %></small>
</div>

</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">Categories listing page</h1>
<div class="flickr_pagination">
    <%= will_paginate @category, :container => false %>
</div>
<div class="container" id="listing-container">
        
        <% @category.each do |category| %>
        <div class="row justify-content-md-center mt-4">
        <div class="col-4 text-center">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title ">
                    <%= link_to category.name, category_path(category), class: "text-success" %></br>
                    <p class="card-text content-center mt-2"><%= pluralize(category.articles.count, "article") %></p>
                </h5>
                
                </div>
                <div class="card-footer text-muted">
                    <small>created <%= time_ago_in_words(category.created_at) %> ago edited <%= time_ago_in_words(category.updated_at) %> ago</small>
                </div>
            </div>
            </div>
        </div>
        <% end %>

    </div>
<div class="flickr_pagination mb-4 mt-4">
    <%= will_paginate @category, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 mb-4">Create new Category</h1>

<div class="container">

<div class="row justify-content-center">
    <div class="col-sm-12">
        <%= render 'form' %>
    </div>
    <small ><%= link_to '[ Cancel and return to Categories Listing ]', categories_path  %></small>
</div>

</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 mb-4">Category: <%= @category.name %></h1>

<% if logged_in? and current_user.admin? %>
<div class="text-center mt-4">
    <%= link_to 'Edit Category Name', edit_category_path(@category), class: "btn btn-outline-info" %>
</div>
<% end %>
<h3 class="text-center mt-4 mb-4"> Articles </h3>
<div class="flickr_pagination">
    <%= will_paginate @article_category, :container => false %>
</div>
<%= render 'articles/articles', obj_article: @article_category %>
<div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @article_category, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<div class="row justify-content-center">
  <div class="col-sm-8">
  
  <% flash.each do |name, msg| %>
    <% if name == "notice" %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">  <%= msg %> </h4>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% else %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">  <%= msg %> </h4>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>    
    <% end %>
    </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Project2', root_path, class: 'navbar-brand', id: 'navlogo' %>
    
    <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Article
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Articles', articles_path, class: 'dropdown-item' %>
                <% if logged_in? %>
                    <%= link_to 'Create new Article', new_article_path, class: 'dropdown-item' %>
                <% end %>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'View Categories', categories_path, class: 'dropdown-item' %>
                <% if logged_in? && current_user.admin? %>
                    <%= link_to 'Create new Categories', new_category_path, class: 'dropdown-item' %>
                <% end %>
            </div>
        </li>
        <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   <%= "[Admin]" if current_user.admin? %> Profile <- <%= current_user.username %> ->
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'View your profile', user_path(current_user), class: 'dropdown-item' %>
                    <%= link_to 'Edit your profile', edit_user_path(current_user), class: 'dropdown-item' %>
                    <%= link_to 'Delete profile', user_path(current_user), class: 'dropdown-item text-danger', method: :delete, data: { confirm: "Are you sure?" } %>
                </div>
            </li>
            <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: 'nav-link', method: :delete %>
            </li>
            
        <% else %>
            <li class="nav-item">
            <%= link_to 'Log In', login_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
            </li>
        <% end %>
        
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>      
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>This is about page</h2>

<%= link_to 'Home', root_path %> | <%= link_to 'Article listing', articles_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
        <div class="jumbotron">
        <h1 class="display-4">Welcome to Project 2</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        
        <%= link_to 'Sign Up', new_user_path, class: "btn btn-primary btn-lg" %>
        </div>

    
    </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="alert-heading">These errors prevent the <%= obj.class.name.downcase %> to be submitied</h4>
  <ul>
<% obj.errors.full_messages.each do |msg| %>
    <li>  <%= msg %>  </li>
<% end %>
</ul>
</div>
<% end %>
<%= puts %>

app/views/users/_form.html.erb
<div class="container">

<div class="row justify-content-center">
    <div class="col-sm-12">
        <%= render "shared/errors", obj: @user %>
        <%= form_with(model: @user, local: true) do |f| %>
        <div class="form-group row justify-content-center">
            <%= f.label :username, class: 'col-sm-2 col-form-label' %></br>
            <div class="col-sm-8">
            <%= f.text_field :username, class: 'form-control', placeholder: "Enter the User Name" %>
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <%= f.label :email, class: 'col-sm-2 col-form-label' %></br>
            <div class="col-sm-8">
            <%= f.email_field :email, class: 'form-control', placeholder: "Enter the Email" %>
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <%= f.label :password, class: 'col-sm-2 col-form-label' %></br>
            <div class="col-sm-8">
            <%= f.password_field :password, class: 'form-control', placeholder: "Enter the Password" %>
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: 'btn btn-outline-success') %>
        </div>
        <% end %>
        </div>
        <small ><%= link_to '[ Cancel and return to Home ]', root_path  %></small>
    
</div>

</div>

app/views/users/_users.html.erb
<div class="container" id="listing-container">    
    <% @users.each do |user| %>
        <div class="row justify-content-md-center mt-4">
            <div class="col-8">
                <div class="card ">
                    <div class="card-header text-center">
                    <%= link_to user.username, user %>
                    </div>
                    <div class="card-body d-block mx-auto text-center">
                        <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
                        <p class="card-text content-center"><%= pluralize(user.articles.count, "article") %></p>
                        <%= link_to 'View Profile', user_path(user), class: "btn btn-outline-success" %>
                        <% if logged_in? %>
                            <% if user == current_user %>    
                                <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-info" %>
                            <% end %>
                            <% if current_user.admin? %>
                                <%= link_to 'Delete Profile', user_path(user), class: "btn btn-outline-danger", 
                                method: :delete, 
                                data: { confirm: "Are you sure want to delete the account and all its assosiated articles"} %>
                            <% end %>                
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>created <%= time_ago_in_words(user.created_at) %> ago edited <%= time_ago_in_words(user.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit your information <%= @user.username.upcase %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-4"> Project2 Users Listing</h1>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
<%= render 'users' %>
<div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4 mb-4">Sign up For Project2</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4 mb-4"><%= @user.username %>'s profile </h1>
<%= gravatar_for @user, size: 200 %>
<% if logged_in? and @user == current_user %>
<div class="text-center mt-4">
    <%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-outline-info" %>
</div>
<% end %>
<h3 class="text-center mt-4 mb-4"> Articles </h3>
<div class="flickr_pagination">
    <%= will_paginate @article, :container => false %>
</div>
<%= render 'articles/articles', obj_article: @article %>
<div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @article, :container => false %>
</div>